name: jahez_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  flutter_image_slideshow: ^0.1.5
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/images/
